version: 2

linters-settings:
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - os.RemoveAll
      - os.Remove
      - os.Setenv

  gocyclo:
    min-complexity: 25

  goconst:
    min-len: 3
    min-occurrences: 3

  staticcheck:
    checks: ["all", "-SA9003"]

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - staticcheck
    - gocyclo
    - goconst
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - goconst
        - staticcheck
        - govet
        - ineffassign
        - unused
        - misspell
        - revive
        - stylecheck
    
    # Ignore package-comments warnings
    - text: "package-comments"
      linters:
        - revive
    
    # Ignore var-naming for utils package
    - text: "var-naming"
      linters:
        - revive
  
  exclude-dirs:
    - vendor
    - builds
  
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 2m
  tests: false
  go: '1.25.4'
