linters-settings:
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - os.RemoveAll
      - os.Remove
      - os.Setenv

  gocyclo:
    min-complexity: 25

  goconst:
    min-len: 3
    min-occurrences: 3

  staticcheck:
    checks: ["all", "-SA9003"]

  revive:
    rules:
      - name: exported
      - name: package-comments
        disabled: true
      - name: var-naming
      - name: function-result-limit
        arguments: [3]

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - staticcheck
    - gocyclo
    - goconst
    - misspell
    - revive
    - stylecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - goconst
        - staticcheck
        - govet
        - ineffassign
        - unused
        - misspell
        - revive
        - stylecheck
  
  exclude-dirs:
    - vendor
    - builds
  
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 2m
  tests: false
  go: '1.25.4'
