version: 2

linters-settings:
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - os.RemoveAll
      - os.Remove
      - os.Setenv

  gocyclo:
    min-complexity: 25

  goconst:
    min-len: 3
    min-occurrences: 3

  staticcheck:
    checks: ["all", "-SA9003"]  # Disable "empty branch" check

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - staticcheck
    - gocyclo
    - goconst
    - misspell

issues:
  exclude-rules:
    # Exclude all linting for test files - they don't need to be perfect
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - goconst
        - staticcheck
        - govet
        - ineffassign
        - unused
        - misspell
  
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 2m
  tests: false  # Don't lint test files
  go: '1.25.3'
  skip-dirs:
    - vendor
    - builds